collective: arsenal
tiers:
  - tiers: "*"
    labels: ["backer"]
    message: "Hey <author> , thanks for supporting us on Open Collective :heart::heart::heart: We'll make sure that this issue is reviewed by a team member!"
